# Web scraping con Beautiful Soup

El **web scraping** es el proceso de extracción de datos de sitios web de manera automatizada. Aprenderás los conceptos fundamentales y las herramientas necesarias para recolectar datos valiosos de la web, lo que te permitirá alimentar tus análisis y proyectos de Data Science con información fresca y relevante.

## ¿Qué es?

En términos sencillos, web scraping es como recolectar datos de una página web. Imagina que la web es una mina de información y que eres un minero recogiendo las gemas que necesitas para tu proyecto. En lugar de copiar y pegar manualmente, utilizamos código para automatizar el proceso.

### ¿Por qué es importante el Web Scraping?

* **Acceso a datos no estructurados**: La mayoría de los datos en línea no están disponibles en formatos estructurados y listos para ser analizados. El web scraping te permite convertir datos no estructurados en un formato que puedas utilizar.

* **Actualización de datos**: Muchas fuentes web se actualizan constantemente. El web scraping te permite mantener tus conjuntos de datos actualizados sin tener que hacerlo manualmente.

* **Amplia gama de aplicaciones**: Desde la recopilación de datos de redes sociales hasta la obtención de precios de productos, el web scraping se utiliza en una amplia gama de aplicaciones de Data Science.

## Proceso de Web Scraping

El web scraping generalmente sigue estos pasos:

* **Hacer una solicitud HTTP**: obtenemos el contenido HTML de una página web.

* **Análisis del HTML**: analizamos la estructura del HTML y encontramos los elementos que contienen los datos que necesitamos.

* **Extracción de datos**: una vez identificados los elementos, extraemos los datos relevantes.

* **Almacenamiento de datos**: guardamos los datos en un formato estructurado, como un archivo CSV o una base de datos.

* **Limpieza y procesamiento**: a menudo, los datos extraídos necesitan ser limpiados y preprocesados antes de su análisis.

### Aspectos legales y éticos

El web scraping puede tener implicaciones legales y éticas. Antes de scrapear una web, revisa:

* **`robots.txt`**: casi todas las webs publican en `https://dominio/robots.txt` qué rutas permiten (`Allow`) o prohíben (`Disallow`) a los robots. No es una ley, pero es la primera señal de lo que el sitio acepta.  

* **Términos de uso**: algunos sitios prohíben expresamente la extracción automatizada de sus datos.
* **Volumen de peticiones**: no sobrecargues el servidor. Haz pausas entre peticiones (`time.sleep`) y descarga solo lo que necesitas.
* **Datos personales**: si extraes datos de personas (nombres, correos, perfiles...), en la UE se aplica el **RGPD**, aunque esos datos sean públicos.
* **Propiedad intelectual**: que un contenido sea accesible no significa que puedas redistribuirlo.
* **¿Hay una API?**: si el sitio ofrece una API oficial, úsala. Es más estable, más eficiente y está permitida.

In [55]:
import requests

robots = requests.get("https://www.filmaffinity.com/robots.txt", timeout=10)
print(robots.text[:1000])

User-agent: *
Disallow: /*?FASID
Disallow: /*&FASID
Disallow: /*/sharerating
Disallow: /*/userratings
Disallow: /*/userrating
Disallow: /*/names-together

## Intro HTML

HTML (HyperText Markup Language) es el lenguaje de marcado utilizado para crear páginas web. Comprender los conceptos básicos de HTML es esencial para realizar web scraping, ya que te permite navegar y extraer datos de manera efectiva de sitios web.

HTML utiliza etiquetas para estructurar el contenido de una página web. Aquí tienes una breve introducción a los conceptos básicos de HTML:

1. **Etiquetas:** Las etiquetas son elementos fundamentales en HTML. Comienzan con `<` y terminan con `>`. Por ejemplo, `<p>` se utiliza para definir un párrafo, `<h1>` para encabezados de nivel 1, y `<a>` para enlaces.

2. **Elementos:** Un elemento HTML se compone de una etiqueta de apertura, contenido y una etiqueta de cierre. Por ejemplo, `<p>Este es un párrafo.</p>`. El contenido es lo que se muestra en la página.

3. **Atributos:** Las etiquetas pueden contener atributos que proporcionan información adicional sobre el elemento. Por ejemplo, en `<a href="https://www.ejemplo.com">Enlace</a>`, "href" es un atributo que define la URL a la que el enlace apunta.

4. **Anidamiento:** Los elementos HTML pueden anidarse dentro de otros elementos. Por ejemplo, un párrafo `<p>` puede contener un enlace `<a>`. Es importante entender la jerarquía de anidamiento para navegar eficazmente por la estructura de una página web.

5. **Estructura:** Una página web típica tiene una estructura jerárquica con elementos como `<html>`, `<head>` (que contiene metadatos), `<body>` (que contiene el contenido visible), y muchos otros elementos como encabezados, listas, imágenes, etc.

6. **Clases e IDs:** Los elementos HTML pueden tener clases y IDs, que son atributos utilizados para aplicar estilos y facilitar la identificación de elementos específicos en una página. Estos son útiles al realizar web scraping para seleccionar elementos específicos.

Para realizar web scraping, necesitas comprender cómo se organiza y etiqueta la información en una página web para poder identificar y extraer los datos que necesitas. El conocimiento de HTML es una base fundamental para esta tarea, ya que te permite navegar y seleccionar elementos específicos en el código fuente de una página web.

![Estructura HTML](./img/html-content-web-scraping.png)

### Ejemplo con un HTML sencillo

Antes de ir a una web real, practiquemos con un HTML pequeño escrito por nosotros. Así vemos las herramientas básicas de BeautifulSoup sobre un documento que **no cambia**, mientras que las webs reales modifican su estructura con frecuencia.

In [56]:
from bs4 import BeautifulSoup as bs
import pandas as pd

html_ejemplo = """
<html>
  <head><title>Mi tienda de libros</title></head>
  <body>
    <h1 id="titulo-principal">Libros destacados</h1>
    <ul id="libros">
      <li class="libro"><a href="/libros/1">Cien años de soledad</a> <span class="precio">12,50</span></li>
      <li class="libro"><a href="/libros/2">Don Quijote de la Mancha</a> <span class="precio">9,95</span></li>
      <li class="libro"><a href="/libros/3">La sombra del viento</a> <span class="precio">15,00</span></li>
    </ul>
  </body>
</html>
"""

soup_ejemplo = bs(html_ejemplo, "html.parser")

print(soup_ejemplo.title.get_text())             # texto de la etiqueta <title>
print(soup_ejemplo.find("h1")["id"])              # atributo id del <h1>
print(soup_ejemplo.find("ul", id="libros").name)  # buscar por etiqueta + atributo



for libro in soup_ejemplo.find_all("li", class_="libro"):
    titulo = libro.find("a").get_text()
    enlace = libro.find("a")["href"]
    precio = float(libro.find("span", class_="precio").get_text().replace(",", "."))
    print(f"{titulo}, {enlace} \t-> {precio} €")

Mi tienda de libros
titulo-principal
ul
Cien años de soledad, /libros/1 	-> 12.5 €
Don Quijote de la Mancha, /libros/2 	-> 9.95 €
La sombra del viento, /libros/3 	-> 15.0 €

### BeautifulSoup

Beautiful Soup es una popular biblioteca de Python utilizada para analizar y extraer información de documentos HTML y XML de una manera sencilla y eficaz. Esta biblioteca proporciona herramientas para navegar y buscar elementos dentro de la estructura de un documento web, lo que la convierte en una herramienta esencial para tareas de web scraping y procesamiento de datos web. Beautiful Soup facilita la extracción de datos de una página web al proporcionar una interfaz amigable que permite acceder a etiquetas, atributos y contenido de manera intuitiva, lo que la convierte en una elección común entre los científicos de datos y desarrolladores que trabajan con datos web.

In [57]:
pip install requests

Requirement already satisfied: requests in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (2.34.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from requests) (3.5.2)
Requirement already satisfied: idna<4,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from requests) (3.20)
Requirement already satisfied: urllib3<3,>=1.26 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from requests) (2.8.0)
Requirement already satisfied: certifi>=2023.5.7 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from requests) (2026.7.22)

[notice] A new release of pip is available: 25.0.1 -> 26.2.1
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [58]:
from bs4 import BeautifulSoup as bs
import requests
import pandas as pd
# from splinter import Browser
import numpy as np

pd.set_option('max_colwidth', 800) # Cantidad de caracteres total que puede haber en una celda

Ahora estamos listos para solicitar nuestra primera página web. No es nada complicado: guardamos la URL que queremos scrapear en la variable `url`, hacemos la petición con `requests.get(url)` y guardamos la respuesta en la variable `response`.

Conviene acostumbrarse desde el principio a tres buenas prácticas:

* **`headers` con `User-Agent`**: por defecto `requests` se identifica como `python-requests/x.y`, y muchas webs bloquean ese agente (respuesta 403). Enviar un `User-Agent` de navegador evita muchos de esos bloqueos.
* **`timeout`**: sin él, si el servidor no responde, la petición puede quedarse colgada indefinidamente.
* **`response.raise_for_status()`**: si la respuesta es un error (403, 404, 429...), lanza una excepción en lugar de seguir trabajando con una página de error sin darnos cuenta.

Además, si vas a hacer **varias peticiones** (por ejemplo, recorrer varias páginas), añade una pausa entre ellas con `time.sleep(1)` o similar para no sobrecargar el servidor ni ser bloqueado.

In [59]:
url = "https://www.filmaffinity.com/es/topgen.php"
headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36"}

response = requests.get(url, headers=headers, timeout=10)
response.raise_for_status()  # lanza una excepción si el código no es 2xx (403, 404, 429, 500...)

In [60]:
print(response)

<Response [200]>

Pero necesitamos el contenido HTML de la página web solicitada, así que como siguiente paso guardamos el contenido de la respuesta en la variable `html`:

In [61]:
html = response.content

In [62]:
print(html)

b'<!DOCTYPE html>\n<!-- New Layout -->\n<html lang="es">\n    <head>\n        <meta charset="UTF-8">\n        \n            <title>Top Filmaffinity: las mejores pel\xc3\xadculas y series de la historia por pa\xc3\xadses - a\xc3\xb1os - g\xc3\xa9nero - Filmaffinity</title>\n            <meta name="description" content="">\n            <link rel="manifest" href="/manifest.json">\n            <meta property="og:site_name" content="FilmAffinity">\n            <link rel="shortcut icon" sizes="144x144" href="/favicon.png">\n            <link rel="apple-touch-icon" href="/favicon.png">\n            <link rel="apple-touch-icon" sizes="76x76" href="/touch-icon-ipad.png">\n            <link rel="apple-touch-icon" sizes="120x120" href="/touch-icon-iphone-retina.png">\n            <link rel="apple-touch-icon" sizes="152x152" href="/touch-icon-ipad-retina.png">\n            <link rel="apple-touch-startup-image" href="/startup.png">\n            <link rel="icon" type="image/png" href="/favicon.png">\n\n<meta property="og:type" content="website" >\n<meta property="og:url" content="https%3A%2F%2Fwww.filmaffinity.com%2Fes%2Ftopgen.php">\n<meta property="og:title" content="Filmaffinity">\n<meta property="og:description" content="Filmaffinity es una web de votaci\xc3\xb3n y recomendaci\xc3\xb3n personalizada de pel\xc3\xadculas y series, una red social y diario del cine y las series con votaciones, listas y cr\xc3\xadticas, y una p\xc3\xa1gina de consulta de cartelera, horarios de entradas de cine y una web con toda la informaci\xc3\xb3n de todas las plataformas y recomendaciones personales basadas en tus gustos. Explora las filmograf\xc3\xadas y carreras art\xc3\xadsticas de m\xc3\xa1s de 1 mill\xc3\xb3n de directores, actores y actrices, descubre los mejores lanzamientos de Netflix, HBO MAX, Amazon Prime Video y otras plataformas por nota media, por popularidad o a\xc3\xb1o de estreno, y compra tus entradas para el cine online en apenas un par de clicks.">\n<meta property="og:image" content="https://filmaffinity.com/images/icon.png" />\n<meta name="twitter:site" content="@Filmaffinity">\n<meta name="twitter:card" content="summary" >\n<meta name="twitter:title" content="Filmaffinity">\n<meta name="twitter:description" content="Filmaffinity es una web de votaci\xc3\xb3n y recomendaci\xc3\xb3n personalizada de pel\xc3\xadculas y series, una red social y diario del cine y las series con votaciones, listas y cr\xc3\xadticas, y una p\xc3\xa1gina de consulta de cartelera, horarios de entradas de cine y una web con toda la informaci\xc3\xb3n de todas las plataformas y recomendaciones personales basadas en tus gustos. Explora las filmograf\xc3\xadas y carreras art\xc3\xadsticas de m\xc3\xa1s de 1 mill\xc3\xb3n de directores, actores y actrices, descubre los mejores lanzamientos de Netflix, HBO MAX, Amazon Prime Video y otras plataformas por nota media, por popularidad o a\xc3\xb1o de estreno, y compra tus entradas para el cine online en apenas un par de clicks.">\n<meta name="twitter:image" content="https://filmaffinity.com/images/icon.png">\n<link rel="alternate" href="https://www.filmaffinity.com/es/topgen.php" hreflang="es">\n<link rel="alternate" href="https://www.filmaffinity.com/en/topgen.php" hreflang="en">\n<link rel="alternate" href="https://www.filmaffinity.com/mx/topgen.php" hreflang="es-MX">\n<link rel="alternate" href="https://www.filmaffinity.com/ar/topgen.php" hreflang="es-AR">\n<link rel="alternate" href="https://www.filmaffinity.com/cl/topgen.php" hreflang="es-CL">\n<link rel="alternate" href="https://www.filmaffinity.com/co/topgen.php" hreflang="es-CO">\n<link rel="alternate" href="https://www.filmaffinity.com/uy/topgen.php" hreflang="es-UY">\n<link rel="alternate" href="https://www.filmaffinity.com/py/topgen.php" hreflang="es-PY">\n<link rel="alternate" href="https://www.filmaffinity.com/pe/topgen.php" hreflang="es-PE">\n<link rel="alternate" href="https://www.filmaffinity.com/ec/topgen.php" hreflang="es-EC">\n<link rel="alternate" href="https://www.filmaffinity.com/ve/topgen.php" hreflang="es-VE">\n<link rel="alternate" href="https://www.filmaffinity.com/cr/topgen.php" hreflang="es-CR">\n<link rel="alternate" href="https://www.filmaffinity.com/hn/topgen.php" hreflang="es-HN">\n<link rel="alternate" href="https://www.filmaffinity.com/gt/topgen.php" hreflang="es-GT">\n<link rel="alternate" href="https://www.filmaffinity.com/bo/topgen.php" hreflang="es-BO">\n<link rel="alternate" href="https://www.filmaffinity.com/do/topgen.php" hreflang="es-DO">\n<link rel="alternate" href="https://www.filmaffinity.com/us/topgen.php" hreflang="en-US">\n<link rel="alternate" href="https://www.filmaffinity.com/uk/topgen.php" hreflang="en-GB">\n<link rel="alternate" href="https://www.filmaffinity.com/ie/topgen.php" hreflang="en-IE">\n<link rel="alternate" href="https://www.filmaffinity.com/au/topgen.php" hreflang="en-AU">\n<link rel="alternate" href="https://www.filmaffinity.com/ca/topgen.php" hreflang="en-CA">\n                <link rel="alternate" media="only screen and (max-width: 640px)" href="https://m.filmaffinity.com/es/topgen.php">\n<script type="text/javascript" src="/js/local_es.1539096293.js"></script>\n<script type="text/javascript" src="/js/ads.1539096293.js"></script>\n<script type="text/javascript" src="/js/crc32.1539096293.js"></script>\n<script type="text/javascript" src="/js/translate-context.1539096293.js"></script>\n<script type="text/javascript" src="/js/locale/texts-es_ES.1790765699.js"></script>\n<script type="text/javascript" src="/js/jquery/jquery-3.7.1.min.1769585555.js"></script>\n<script type="text/javascript" src="/js/bootstrap/bootstrap.bundle.min.5.3.2.1694701167.js"></script>\n<link href="/style/bootstrap/fa-theme.5.3.2.1791978410.css" rel="stylesheet" type="text/css">\n<link href="/style/main3.1773834909.css" rel="stylesheet" type="text/css">\n<link href="/style/moviecards3.1719569557.css" rel="stylesheet" type="text/css">\n<link href="/style/all.min.1731580891.css" rel="stylesheet" type="text/css">\n<link href="/style/fa-icons.1676894187.css" rel="stylesheet" type="text/css">\n<link href="/style/magic-check.min.1539096291.css" rel="stylesheet" type="text/css">\n<link href="/style/bootstrap/fa-top.min.1791359023.css" rel="stylesheet" type="text/css">\n<link href="/style/jquery/slider/bootstrap-slider.min.1631702791.css" rel="stylesheet" type="text/css">\n<script type="text/javascript" src="/js/jquery/plugin/slider/bootstrap-slider.min.1631702815.js"></script>\n<link href="/style/jquery/slick/slick.1651839967.css" rel="stylesheet" type="text/css">\n<link href="/style/jquery/slick/slick-theme.1740125949.css" rel="stylesheet" type="text/css">\n<script type="text/javascript" src="/js/jquery/plugin/slick/slick.min.1651839936.js"></script>\n<script type="text/javascript" src="/js/jquery/plugin/new-autocomplete/fa-autocomplete2.1784014157.js"></script>\n<script type="text/javascript" src="/js/jquery/plugin/autocomplete/jquery.easy-autocomplete.1671723118.js"></script>\n<script type="text/javascript" src="/js/bootstrap/bootstrap-autocomplete.1706000471.js"></script>\n<link href="/style/jquery/autocomplete/easy-autocomplete.min.1585727670.css" rel="stylesheet" type="text/css">\n<link href="/style/jquery/autocomplete/easy-autocomplete.themes.min.1585727670.css" rel="stylesheet" type="text/css">\n<link href="/style/jquery/new-autocomplete/fa-autocomplete.1757321028.css" rel="stylesheet" type="text/css">\n<script type="text/javascript" src="/js/fa-sort-pop.class.1775639913.js"></script>\n<link href="/style/jquery/swiper/swiper-bundle.min.1706000643.css" rel="stylesheet" type="text/css">\n<script type="text/javascript" src="/js/jquery/plugin/swiper/swiper-bundle.min.1706000662.js"></script>\n<script type="text/javascript" src="/js/fa-swiper.class.1777892494.js"></script>\n<script type="text/javascript" src="/js/jquery/plugin/dompurify/purify.min.1737551546.js"></script>\n<script type="text/javascript" src="/js/main.1782986644.js"></script>\n<script type="text/javascript" src="/js/pagetop.1668696477.js"></script>\n<script type="text/javascript" src="/js/z-index-fix.1773836800.js"></script>\n<script type="text/javascript" src="/js/jquery/plugin/lazysizes/lazysizes.min.1602068375.js"></script>\n<script type="text/javascript" src="/js/fa-lists-tip.1770898183.js"></script>\n<script type="text/javascript" src="/js/nav.class.1739967269.js"></script>\n<script type="text/javascript" src="/js/jquery/plugin/jquery.cookie.1539096308.js"></script>\n<link href="/style/bootstrap/fa-top.min.1791359023.css" rel="stylesheet" type="text/css">\n<script type="text/javascript" src="/js/movies-rated-filter.class.1792477853.js"></script>\n<script type="text/javascript" src="/js/topgen.1792477782.js"></script>\n<script type="text/javascript" src="/js/mobile-side-pop.1781242591.js"></script>\n<script type="text/javascript" src="/js/quantcast.1773655210.js"></script>\n\n        <script>favars = {"topgenSortFilterData":{"sort":{"header":"<i class=\\"fas fa-sort\\"><\\/i> Ordenar por","options":{"avg-desc":{"name":"orderby","text":"Nota media (descendente)","checked":true},"avg-asc":{"name":"orderby","text":"Nota media (ascendente)"},"rc-desc":{"name":"orderby","text":"N\\u00ba de votos"}}}},"tmPageSize":30,"tmResCount":60730,"tmFrom":0,"flagsConfig":{"full":{"flags":"","sliderruntime":{"ticks":[0,20,30,45,60,90,120,1000],"labels":["0","20","30","45min","60","90","120","+120"],"positions":[0,12,25,40,55,70,85,100]},"subfilters":[]},"movie":{"flags":"*movie, -documentary, -show, -concert","sliderruntime":{"ticks":[0,60,90,120,1000],"labels":["0","60min","90","120","+120"],"positions":[0,30,50,70,100]},"subfilters":[{"type":"checkbox","options":{"ex-anim":"-animation, -interactive, -short","ex-tv":"-tv, -serie, -show, -episode, -miniserie"},"defaults":[]}]},"serie":{"flags":"+serie, +miniserie, +episode, +tv","sliderruntime":{"ticks":[0,20,40,60,1000],"labels":["0","20","40","60min","+60"],"positions":[0,20,40,70,100]},"subfilters":[{"type":"radio","options":{"only-serie":"*serie, -miniserie","only-miniserie":"*miniserie","only-episode":"*episode","only-telefilm":"*tv"},"defaults":[]}]},"documentary":{"flags":"*documentary,-concert,-show","sliderruntime":{"ticks":[0,5,10,20,40,60,90,120,1000],"labels":["0","5","10","20","40","60min","90","120","+120"],"positions":[0,10,20,30,45,60,75,85,100]},"subfilters":[{"type":"checkbox","options":{"ex-serie":"-tv, -serie, -show, -episode, -miniserie","ex-short":"-short, -medio"},"defaults":[]}]},"short":{"flags":"+short,+medio,-tv,-serie,-episode,-miniserie,-musicvideo","sliderruntime":{"ticks":[0,3,5,10,15,20,25,30,45,1000],"labels":["0",">3","5","10","15","20","25","30","45","+45"],"positions":[0,8,20,30,40,50,60,70,85,100]},"subfilters":[{"type":"radio","options":{"all":"","only-docu":"*documentary","only-animation":"*animation"},"defaults":["all"]}]},"animation":{"flags":"*animation","sliderruntime":{"ticks":[0,5,10,20,40,60,90,120,1000],"labels":["0","5","10","20","40min","60","90","120","+120"],"positions":[0,10,20,30,40,60,80,90,100]},"subfilters":[{"type":"radio","options":{"all":"","only-movie":"*movie","only-serie":"+serie,+miniserie","only-short":"*short"},"defaults":["all"]}]},"music":{"flags":"+musicvideo, +concert","sliderruntime":{"ticks":[0,5,10,60,1000],"labels":["0","5","10","60min","+120"],"positions":[0,20,40,70,100]},"subfilters":[{"type":"radio","options":{"all":"","only-musicvideo":"*musicvideo","only-concert":"*concert"},"defaults":["all"]}]}},"filter":{"primaryCountries":null,"genres":null,"fromYear":1874,"toYear":2026,"runtimeMin":0,"runtimeMax":7,"minRatingCount":1,"movieFilterForm":"full","platforms":null,"orderby":"avg"},"lastFilter":null,"defaultFilter":{"movieFilterForm":"full","fromYear":1874,"toYear":2026,"genres":[],"minRatingCount":1,"primaryCountries":0,"runtimeMin":0,"runtimeMax":7,"platforms":[]},"minRatingValues":[20,100,500,1000],"maxPlatforms":15,"myPlatforms":[],"lang":"es","loc":"es","captchaType":"CLOUDFARE_INVISIBLE"};</script>\n\n\n            <script>\n                $(function(){\n                    sessPing("016ad7400c610e3838ed76db3fa770d3aee6cc5839", 2400);\n                    var tcTexts = TranslateContext.getInstance(commonTextsJs);\n                });\n            </script>\n\n\r\n<script>\r\n              window.sc_versionescritorio_from_mobile_fa = 0;\r\n</script>\r\n<script async src="https://securepubads.g.doubleclick.net/tag/js/gpt.js"></script>\r\n\r\n <script>\r\n\r\n        var googletag = googletag || {};\r\n\r\n        googletag.cmd = googletag.cmd || [];\r\n\r\n </script>\r\n\r\n <script src="https://sc-devel.s3.eu-central-1.amazonaws.com/Skins/SMCService.js"></script>\r\n\r\n <script src="https://sc-devel.s3.eu-central-1.amazonaws.com/sc-tagmanager/filmaffinity.js"></script>\r\n\r\n <script src="https://cdn.smartclip-services.com/v1/Storage-a482323/smartclip-services/HeaderBidding/js/SmartclipConfig.js" async="async"></script>\r\n\r\n <script>\r\n  var sc = document.createElement ("script")\r\n  sc.src="https://cdn.smartclip-services.com/v1/Storage-a482323/smartclip-services/wrappers/sc__sync.js"\r\n  sc.onload = function(){\r\n  __sc__sync(["e40c3a8c-532f-469b-8e2a-1cc44f47c967"]) // id de la zona\r\n  }\r\n  document.head.appendChild(sc)\r\n</script>\n\r\n<script>$(function(){sendpv("524222d62ebe4a373d7c00f523eb137e");});</script>\r\n\n    </head>\n\n\n\n    <body>\n        <!-- Google tag (gtag.js) -->\n<script async src="https://www.googletagmanager.com/gtag/js?id=G-TZX5NYMKZC"></script>\n<script>\n  window.dataLayer = window.dataLayer || [];\n  function gtag(){dataLayer.push(arguments);}\n  gtag(\'js\', new Date());\n\n  gtag(\'config\', \'G-TZX5NYMKZC\');\n</script>\n\n<header id="page-header">\n    <div id="header-top" >\n        <div class="cpanel top-wrapper">\n            <div id="logo-container">\n                <a href="https://www.filmaffinity.com/es/main.html">\n                    <img alt="logo" src="/images/logo4.png">\n                    <div class="logo-siteloc">Espa\xc3\xb1a</div>\n                </a>\n            </div><!-- logo-container -->\n\n\n            <div class="search-box">\n                <div id="topsearch-ac" class="s-large">\n                    <form name="search-form" action="https://www.filmaffinity.com/es/search.php" method="get" accept-charset="UTF-8" data-ftoken="6bf12c7f9abec9e292f38ff763300b220443f627bd3551bee93d85c90e720a46">\n                        <input id="top-search-input-2" class="s-large" type="text" name="stext" size="20" value="" tabindex="1" placeholder="Buscar">\n                    </form>\n                    <div class="s-load fa-3x"><i class="fa-regular fa-spinner-third fa-spin"></i></div>\n                    <i class="fa-light fa-times clear-search" style="display: none;"></i>\n                    <div class="search-btn"><i class="fa-light fa-magnifying-glass"></i></div>\n                    <div class="advsearch"><a href="https://www.filmaffinity.com/es/advsearch.php">B\xc3\xbasqueda avanzada <i class="fa-solid fa-angle-double-right"></i></a></div>\n                </div><!-- topsearch -->\n            </div><!--search-box -->\n\n\n            <div id="user-login-container">\n                    <div id="login-register">\n                        <a class="sign-in" href="https://www.filmaffinity.com/es/login.php"><strong>Iniciar sesi\xc3\xb3n</strong></a> / <a class="register" href="https://www.filmaffinity.com/es/register.php">Registrarse</a>\n                    </div>\n            </div><!-- user-login -container -->\n        </div>\n    </div><!-- header-top -->\n\n\n    <div id="header-bottom" class=" ">\n        <div class="cpanel news-wrapper">\n<ul id="awardsmenu">\n                <li ><a href="https://www.filmaffinity.com/es/topgen.php">Top FA</a></li><li class="sep">|</li>\n                <li ><a href="https://www.filmaffinity.com/es/rankings.php">Rankings FA</a></li><li class="sep">|</li>\n                <li ><a href="https://www.filmaffinity.com/es/calendar-tv.php">Calendario Series</a></li><li class="sep">|</li>\n                <li ><a href="https://www.filmaffinity.com/es/category.php?id=TRAILERS">Tr\xc3\xa1ilers</a></li><li class="sep">|</li>\n                <li ><a href="https://www.filmaffinity.com/es/category.php?id=latest_reviews">Cr\xc3\xadticas</a></li><li class="sep">|</li>\n                <li ><a href="https://www.filmaffinity.com/es/best_2025.php">2025</a></li><li class="sep">|</li>\n                <li ><a href="https://www.filmaffinity.com/es/category.php?id=2026films">2026</a></li><li class="sep">|</li>\n                <li ><a href="https://www.filmaffinity.com/es/all_awards.php">Premios</a></li><li class="sep">|</li>\n                <li ><a href="https://www.filmaffinity.com/es/cinema-guide.php">Gu\xc3\xada FilmAffinity <span class=tooltip-new>New</span></a></li><li class="sep">|</li>\n</ul>\n                <div id="trmenu">\n                    <div id="tw-top-logo" class="social-logo"><a target="_blank" rel="noopener noreferrer" title="Sigue a FA en Twitter (75.000 followers)" href="https://twitter.com/Filmaffinity"><i class="fa-brands fa-x-twitter"></i></a></div>\n                    <div id="in-top-logo" class="social-logo"><a target="_blank" rel="noopener noreferrer" title="Sigue a FA en Instagram (155.000 followers)" href="https://www.instagram.com/filmaffinity/"><i class="fa-brands fa-instagram"></i></a></div>\n                </div>\n\n            <div class="version-selector">\n                <ul class="version">\n                    <li data-version="es" class="fixed" title="Cambiar de versi\xc3\xb3n">Espa\xc3\xb1a <i class="fa-solid fa-chevron-down"></i></li>\n                </ul>\n            </div><!-- version-selector -->\n\n\r\n<div class="page-versions-pop fa-shadow">\r\n    <div class="country-names">\r\n        <ul class="continents">\r\n                <li data-continent="america-north">\r\n                    <div class="header">Norteam\xc3\xa9rica <i class="fa-solid fa-search-plus map-zoom"></i></div>\r\n                    <ul class="countries">\r\n                            <li data-version="us" data-country-id="us"><img class="nflag" src="/imgs/countries2/US.png" alt="Estados Unidos"> US <i class="fa-solid fa-arrow-right go-to-version"></i></li>\r\n                            <li data-version="ca" data-country-id="ca"><img class="nflag" src="/imgs/countries2/CA.png" alt="Canad\xc3\xa1"> Canad\xc3\xa1 <i class="fa-solid fa-arrow-right go-to-version"></i></li>\r\n                            <li data-version="mx" data-country-id="mx"><img class="nflag" src="/imgs/countries2/MX.png" alt="M\xc3\xa9xico"> M\xc3\xa9xico <i class="fa-solid fa-arrow-right go-to-version"></i></li>\r\n                    </ul>\r\n                </li>\r\n                <li data-continent="europe">\r\n                    <div class="header">Europa <i class="fa-solid fa-search-plus map-zoom"></i></div>\r\n                    <ul class="countries">\r\n                            <li data-version="es" data-country-id="es"><img class="nflag" src="/imgs/countries2/ES.png" alt="Espa\xc3\xb1a"> Espa\xc3\xb1a <i class="fa-solid fa-arrow-right go-to-version"></i></li>\r\n                            <li data-version="uk" data-country-id="gb"><img class="nflag" src="/imgs/countries2/GB.png" alt="Reino Unido"> UK <i class="fa-solid fa-arrow-right go-to-version"></i></li>\r\n                            <li data-version="ie" data-country-id="ie"><img class="nflag" src="/imgs/countries2/IE.png" alt="Irlanda"> Irlanda <i class="fa-solid fa-arrow-right go-to-version"></i></li>\r\n                    </ul>\r\n                </li>\r\n                <li data-continent="oceania">\r\n                    <div class="header">Ocean\xc3\xada <i class="fa-solid fa-search-plus map-zoom"></i></div>\r\n                    <ul class="countries">\r\n                            <li data-version="au" data-country-id="au"><img class="nflag" src="/imgs/countries2/AU.png" alt="A

In [63]:
soup = bs(html, 'html.parser')

In [64]:
print(soup)

<!DOCTYPE html>

<!-- New Layout -->
<html lang="es">
<head>
<meta charset="utf-8"/>
<title>Top Filmaffinity: las mejores películas y series de la historia por países - años - género - Filmaffinity</title>
<meta content="" name="description"/>
<link href="/manifest.json" rel="manifest"/>
<meta content="FilmAffinity" property="og:site_name"/>
<link href="/favicon.png" rel="shortcut icon" sizes="144x144"/>
<link href="/favicon.png" rel="apple-touch-icon"/>
<link href="/touch-icon-ipad.png" rel="apple-touch-icon" sizes="76x76"/>
<link href="/touch-icon-iphone-retina.png" rel="apple-touch-icon" sizes="120x120"/>
<link href="/touch-icon-ipad-retina.png" rel="apple-touch-icon" sizes="152x152"/>
<link href="/startup.png" rel="apple-touch-startup-image"/>
<link href="/favicon.png" rel="icon" type="image/png"/>
<meta content="website" property="og:type"/>
<meta content="https%3A%2F%2Fwww.filmaffinity.com%2Fes%2Ftopgen.php" property="og:url"/>
<meta content="Filmaffinity" property="og:title"/>
<meta content="Filmaffinity es una web de votación y recomendación personalizada de películas y series, una red social y diario del cine y las series con votaciones, listas y críticas, y una página de consulta de cartelera, horarios de entradas de cine y una web con toda la información de todas las plataformas y recomendaciones personales basadas en tus gustos. Explora las filmografías y carreras artísticas de más de 1 millón de directores, actores y actrices, descubre los mejores lanzamientos de Netflix, HBO MAX, Amazon Prime Video y otras plataformas por nota media, por popularidad o año de estreno, y compra tus entradas para el cine online en apenas un par de clicks." property="og:description"/>
<meta content="https://filmaffinity.com/images/icon.png" property="og:image"/>
<meta content="@Filmaffinity" name="twitter:site"/>
<meta content="summary" name="twitter:card"/>
<meta content="Filmaffinity" name="twitter:title"/>
<meta content="Filmaffinity es una web de votación y recomendación personalizada de películas y series, una red social y diario del cine y las series con votaciones, listas y críticas, y una página de consulta de cartelera, horarios de entradas de cine y una web con toda la información de todas las plataformas y recomendaciones personales basadas en tus gustos. Explora las filmografías y carreras artísticas de más de 1 millón de directores, actores y actrices, descubre los mejores lanzamientos de Netflix, HBO MAX, Amazon Prime Video y otras plataformas por nota media, por popularidad o año de estreno, y compra tus entradas para el cine online en apenas un par de clicks." name="twitter:description"/>
<meta content="https://filmaffinity.com/images/icon.png" name="twitter:image"/>
<link href="https://www.filmaffinity.com/es/topgen.php" hreflang="es" rel="alternate"/>
<link href="https://www.filmaffinity.com/en/topgen.php" hreflang="en" rel="alternate"/>
<link href="https://www.filmaffinity.com/mx/topgen.php" hreflang="es-MX" rel="alternate"/>
<link href="https://www.filmaffinity.com/ar/topgen.php" hreflang="es-AR" rel="alternate"/>
<link href="https://www.filmaffinity.com/cl/topgen.php" hreflang="es-CL" rel="alternate"/>
<link href="https://www.filmaffinity.com/co/topgen.php" hreflang="es-CO" rel="alternate"/>
<link href="https://www.filmaffinity.com/uy/topgen.php" hreflang="es-UY" rel="alternate"/>
<link href="https://www.filmaffinity.com/py/topgen.php" hreflang="es-PY" rel="alternate"/>
<link href="https://www.filmaffinity.com/pe/topgen.php" hreflang="es-PE" rel="alternate"/>
<link href="https://www.filmaffinity.com/ec/topgen.php" hreflang="es-EC" rel="alternate"/>
<link href="https://www.filmaffinity.com/ve/topgen.php" hreflang="es-VE" rel="alternate"/>
<link href="https://www.filmaffinity.com/cr/topgen.php" hreflang="es-CR" rel="alternate"/>
<link href="https://www.filmaffinity.com/hn/topgen.php" hreflang="es-HN" rel="alternate"/>
<link href="https://www.filmaffinity.com/gt/topgen.php" hreflang="es-GT" rel="alternate"/>
<link href="https://www.filmaffinity.com/bo/topgen.php" hreflang="es-BO" rel="alternate"/>
<link href="https://www.filmaffinity.com/do/topgen.php" hreflang="es-DO" rel="alternate"/>
<link href="https://www.filmaffinity.com/us/topgen.php" hreflang="en-US" rel="alternate"/>
<link href="https://www.filmaffinity.com/uk/topgen.php" hreflang="en-GB" rel="alternate"/>
<link href="https://www.filmaffinity.com/ie/topgen.php" hreflang="en-IE" rel="alternate"/>
<link href="https://www.filmaffinity.com/au/topgen.php" hreflang="en-AU" rel="alternate"/>
<link href="https://www.filmaffinity.com/ca/topgen.php" hreflang="en-CA" rel="alternate"/>
<link href="https://m.filmaffinity.com/es/topgen.php" media="only screen and (max-width: 640px)" rel="alternate"/>
<script src="/js/local_es.1539096293.js" type="text/javascript"></script>
<script src="/js/ads.1539096293.js" type="text/javascript"></script>
<script src="/js/crc32.1539096293.js" type="text/javascript"></script>
<script src="/js/translate-context.1539096293.js" type="text/javascript"></script>
<script src="/js/locale/texts-es_ES.1790765699.js" type="text/javascript"></script>
<script src="/js/jquery/jquery-3.7.1.min.1769585555.js" type="text/javascript"></script>
<script src="/js/bootstrap/bootstrap.bundle.min.5.3.2.1694701167.js" type="text/javascript"></script>
<link href="/style/bootstrap/fa-theme.5.3.2.1791978410.css" rel="stylesheet" type="text/css"/>
<link href="/style/main3.1773834909.css" rel="stylesheet" type="text/css"/>
<link href="/style/moviecards3.1719569557.css" rel="stylesheet" type="text/css"/>
<link href="/style/all.min.1731580891.css" rel="stylesheet" type="text/css"/>
<link href="/style/fa-icons.1676894187.css" rel="stylesheet" type="text/css"/>
<link href="/style/magic-check.min.1539096291.css" rel="stylesheet" type="text/css"/>
<link href="/style/bootstrap/fa-top.min.1791359023.css" rel="stylesheet" type="text/css"/>
<link href="/style/jquery/slider/bootstrap-slider.min.1631702791.css" rel="stylesheet" type="text/css"/>
<script src="/js/jquery/plugin/slider/bootstrap-slider.min.1631702815.js" type="text/javascript"></script>
<link href="/style/jquery/slick/slick.1651839967.css" rel="stylesheet" type="text/css"/>
<link href="/style/jquery/slick/slick-theme.1740125949.css" rel="stylesheet" type="text/css"/>
<script src="/js/jquery/plugin/slick/slick.min.1651839936.js" type="text/javascript"></script>
<script src="/js/jquery/plugin/new-autocomplete/fa-autocomplete2.1784014157.js" type="text/javascript"></script>
<script src="/js/jquery/plugin/autocomplete/jquery.easy-autocomplete.1671723118.js" type="text/javascript"></script>
<script src="/js/bootstrap/bootstrap-autocomplete.1706000471.js" type="text/javascript"></script>
<link href="/style/jquery/autocomplete/easy-autocomplete.min.1585727670.css" rel="stylesheet" type="text/css"/>
<link href="/style/jquery/autocomplete/easy-autocomplete.themes.min.1585727670.css" rel="stylesheet" type="text/css"/>
<link href="/style/jquery/new-autocomplete/fa-autocomplete.1757321028.css" rel="stylesheet" type="text/css"/>
<script src="/js/fa-sort-pop.class.1775639913.js" type="text/javascript"></script>
<link href="/style/jquery/swiper/swiper-bundle.min.1706000643.css" rel="stylesheet" type="text/css"/>
<script src="/js/jquery/plugin/swiper/swiper-bundle.min.1706000662.js" type="text/javascript"></script>
<script src="/js/fa-swiper.class.1777892494.js" type="text/javascript"></script>
<script src="/js/jquery/plugin/dompurify/purify.min.1737551546.js" type="text/javascript"></script>
<script src="/js/main.1782986644.js" type="text/javascript"></script>
<script src="/js/pagetop.1668696477.js" type="text/javascript"></script>
<script src="/js/z-index-fix.1773836800.js" type="text/javascript"></script>
<script src="/js/jquery/plugin/lazysizes/lazysizes.min.1602068375.js" type="text/javascript"></script>
<script src="/js/fa-lists-tip.1770898183.js" type="text/javascript"></script>
<script src="/js/nav.class.1739967269.js" type="text/javascript"></script>
<script src="/js/jquery/plugin/jquery.cookie.1539096308.js" type="text/javascript"></script>
<link href="/style/bootstrap/fa-top.min.1791359023.css" rel="stylesheet" type="text/css"/>
<script src="/js/movies-rated-filter.class.1792477853.js" type="text/javascript"></script>
<script src="/js/topgen.1792477782.js" type="text/javascript"></script>
<script src="/js/mobile-side-pop.1781242591.js" type="text/javascript"></script>
<script src="/js/quantcast.1773655210.js" type="text/javascript"></script>
<script>favars = {"topgenSortFilterData":{"sort":{"header":"<i class=\"fas fa-sort\"><\/i> Ordenar por","options":{"avg-desc":{"name":"orderby","text":"Nota media (descendente)","checked":true},"avg-asc":{"name":"orderby","text":"Nota media (ascendente)"},"rc-desc":{"name":"orderby","text":"N\u00ba de votos"}}}},"tmPageSize":30,"tmResCount":60730,"tmFrom":0,"flagsConfig":{"full":{"flags":"","sliderruntime":{"ticks":[0,20,30,45,60,90,120,1000],"labels":["0","20","30","45min","60","90","120","+120"],"positions":[0,12,25,40,55,70,85,100]},"subfilters":[]},"movie":{"flags":"*movie, -documentary, -show, -concert","sliderruntime":{"ticks":[0,60,90,120,1000],"labels":["0","60min","90","120","+120"],"positions":[0,30,50,70,100]},"subfilters":[{"type":"checkbox","options":{"ex-anim":"-animation, -interactive, -short","ex-tv":"-tv, -serie, -show, -episode, -miniserie"},"defaults":[]}]},"serie":{"flags":"+serie, +miniserie, +episode, +tv","sliderruntime":{"ticks":[0,20,40,60,1000],"labels":["0","20","40","60min","+60"],"positions":[0,20,40,70,100]},"subfilters":[{"type":"radio","options":{"only-serie":"*serie, -miniserie","only-miniserie":"*miniserie","only-episode":"*episode","only-telefilm":"*tv"},"defaults":[]}]},"documentary":{"flags":"*documentary,-concert,-show","sliderruntime":{"ticks":[0,5,10,20,40,60,90,120,1000],"labels":["0","5","10","20","40","60min","90","120","+120"],"positions":[0,10,20,30,45,60,75,85,100]},"subfilters":[{"type":"checkbox","options":{"ex-serie":"-tv, -serie, -show, -episode, -miniserie","ex-short":"-short, -medio"},"defaults":[]}]},"short":{"flags":"+short,+medio,-tv,-serie,-episode,-miniserie,-musicvideo","sliderruntime":{"ticks":[0,3,5,10,15,20,25,30,45,1000],"labels":["0",">3","5","10","15","20","25","30","45","+45"],"positions":[0,8,20,30,40,50,60,70,85,100]},"subfilters":[{"type":"radio","options":{"all":"","only-docu":"*documentary","only-animation":"*animation"},"defaults":["all"]}]},"animation":{"flags":"*animation","sliderruntime":{"ticks":[0,5,10,20,40,60,90,120,1000],"labels":["0","5","10","20","40min","60","90","120","+120"],"positions":[0,10,20,30,40,60,80,90,100]},"subfilters":[{"type":"radio","options":{"all":"","only-movie":"*movie","only-serie":"+serie,+miniserie","only-short":"*short"},"defaults":["all"]}]},"music":{"flags":"+musicvideo, +concert","sliderruntime":{"ticks":[0,5,10,60,1000],"labels":["0","5","10","60min","+120"],"positions":[0,20,40,70,100]},"subfilters":[{"type":"radio","options":{"all":"","only-musicvideo":"*musicvideo","only-concert":"*concert"},"defaults":["all"]}]}},"filter":{"primaryCountries":null,"genres":null,"fromYear":1874,"toYear":2026,"runtimeMin":0,"runtimeMax":7,"minRatingCount":1,"movieFilterForm":"full","platforms":null,"orderby":"avg"},"lastFilter":null,"defaultFilter":{"movieFilterForm":"full","fromYear":1874,"toYear":2026,"genres":[],"minRatingCount":1,"primaryCountries":0,"runtimeMin":0,"runtimeMax":7,"platforms":[]},"minRatingValues":[20,100,500,1000],"maxPlatforms":15,"myPlatforms":[],"lang":"es","loc":"es","captchaType":"CLOUDFARE_INVISIBLE"};</script>
<script>
                $(function(){
                    sessPing("016ad7400c610e3838ed76db3fa770d3aee6cc5839", 2400);
                    var tcTexts = TranslateContext.getInstance(commonTextsJs);
                });
            </script>
<script>
              window.sc_versionescritorio_from_mobile_fa = 0;
</script>
<script async="" src="https://securepubads.g.doubleclick.net/tag/js/gpt.js"></script>
<script>

        var googletag = googletag || {};

        googletag.cmd = googletag.cmd || [];

 </script>
<script src="https://sc-devel.s3.eu-central-1.amazonaws.com/Skins/SMCService.js"></script>
<script src="https://sc-devel.s3.eu-central-1.amazonaws.com/sc-tagmanager/filmaffinity.js"></script>
<script async="async" src="https://cdn.smartclip-services.com/v1/Storage-a482323/smartclip-services/HeaderBidding/js/SmartclipConfig.js"></script>
<script>
  var sc = document.createElement ("script")
  sc.src="https://cdn.smartclip-services.com/v1/Storage-a482323/smartclip-services/wrappers/sc__sync.js"
  sc.onload = function(){
  __sc__sync(["e40c3a8c-532f-469b-8e2a-1cc44f47c967"]) // id de la zona
  }
  document.head.appendChild(sc)
</script>
<script>$(function(){sendpv("524222d62ebe4a373d7c00f523eb137e");});</script>
</head>
<body>
<!-- Google tag (gtag.js) -->
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-TZX5NYMKZC"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-TZX5NYMKZC');
</script>
<header id="page-header">
<div id="header-top">
<div class="cpanel top-wrapper">
<div id="logo-container">
<a href="https://www.filmaffinity.com/es/main.html">
<img alt="logo" src="/images/logo4.png"/>
<div class="logo-siteloc">España</div>
</a>
</div><!-- logo-container -->
<div class="search-box">
<div class="s-large" id="topsearch-ac">
<form accept-charset="UTF-8" action="https://www.filmaffinity.com/es/search.php" data-ftoken="6bf12c7f9abec9e292f38ff763300b220443f627bd3551bee93d85c90e720a46" method="get" name="search-form">
<input class="s-large" id="top-search-input-2" name="stext" placeholder="Buscar" size="20" tabindex="1" type="text" value=""/>
</form>
<div class="s-load fa-3x"><i class="fa-regular fa-spinner-third fa-spin"></i></div>
<i class="fa-light fa-times clear-search" style="display: none;"></i>
<div class="search-btn"><i class="fa-light fa-magnifying-glass"></i></div>
<div class="advsearch"><a href="https://www.filmaffinity.com/es/advsearch.php">Búsqueda avanzada <i class="fa-solid fa-angle-double-right"></i></a></div>
</div><!-- topsearch -->
</div><!--search-box -->
<div id="user-login-container">
<div id="login-register">
<a class="sign-in" href="https://www.filmaffinity.com/es/login.php"><strong>Iniciar sesión</strong></a> / <a class="register" href="https://www.filmaffinity.com/es/register.php">Registrarse</a>
</div>
</div><!-- user-login -container -->
</div>
</div><!-- header-top -->
<div class="" id="header-bottom">
<div class="cpanel news-wrapper">
<ul id="awardsmenu">
<li><a href="https://www.filmaffinity.com/es/topgen.php">Top FA</a></li><li class="sep">|</li>
<li><a href="https://www.filmaffinity.com/es/rankings.php">Rankings FA</a></li><li class="sep">|</li>
<li><a href="https://www.filmaffinity.com/es/calendar-tv.php">Calendario Series</a></li><li class="sep">|</li>
<li><a href="https://www.filmaffinity.com/es/category.php?id=TRAILERS">Tráilers</a></li><li class="sep">|</li>
<li><a href="https://www.filmaffinity.com/es/category.php?id=latest_reviews">Críticas</a></li><li class="sep">|</li>
<li><a href="https://www.filmaffinity.com/es/best_2025.php">2025</a></li><li class="sep">|</li>
<li><a href="https://www.filmaffinity.com/es/category.php?id=2026films">2026</a></li><li class="sep">|</li>
<li><a href="https://www.filmaffinity.com/es/all_awards.php">Premios</a></li><li class="sep">|</li>
<li><a href="https://www.filmaffinity.com/es/cinema-guide.php">Guía FilmAffinity <span class="tooltip-new">New</span></a></li><li class="sep">|</li>
</ul>
<div id="trmenu">
<div class="social-logo" id="tw-top-logo"><a href="https://twitter.com/Filmaffinity" rel="noopener noreferrer" target="_blank" title="Sigue a FA en Twitter (75.000 followers)"><i class="fa-brands fa-x-twitter"></i></a></div>
<div class="social-logo" id="in-top-logo"><a href="https://www.instagram.com/filmaffinity/" rel="noopener noreferrer" target="_blank" title="Sigue a FA en Instagram (155.000 followers)"><i class="fa-brands fa-instagram"></i></a></div>
</div>
<div class="version-selector">
<ul class="version">
<li class="fixed" data-version="es" title="Cambiar de versión">España <i class="fa-solid fa-chevron-down"></i></li>
</ul>
</div><!-- version-selector -->
<div class="page-versions-pop fa-shadow">
<div class="country-names">
<ul class="continents">
<li data-continent="america-north">
<div class="header">Norteamérica <i class="fa-solid fa-search-plus map-zoom"></i></div>
<ul class="countries">
<li data-country-id="us" data-version="us"><img alt="Estados Unidos" class="nflag" src="/imgs/countries2/US.png"/> US <i class="fa-solid fa-arrow-right go-to-version"></i></li>
<li data-country-id="ca" data-version="ca"><img alt="Canadá" class="nflag" src="/imgs/countries2/CA.png"/> Canadá <i class="fa-solid fa-arrow-right go-to-version"></i></li>
<li data-country-id="mx" data-version="mx"><img alt="México" class="nflag" src="/imgs/countries2/MX.png"/> México <i class="fa-solid fa-arrow-right go-to-version"></i></li>
</ul>
</li>
<li data-continent="europe">
<div class="header">Europa <i class="fa-solid fa-search-plus map-zoom"></i></div>
<ul class="countries">
<li data-country-id="es" data-version="es"><img alt="España" class="nflag" src="/imgs/countries2/ES.png"/> España <i class="fa-solid fa-arrow-right go-to-version"></i></li>
<li data-country-id="gb" data-version="uk"><img alt="Reino Unido" class="nflag" src="/imgs/countries2/GB.png"/> UK <i class="fa-solid fa-arrow-right go-to-version"></i></li>
<li data-country-id="ie" data-version="ie"><img alt="Irlanda" class="nflag" src="/imgs/countries2/IE.png"/> Irlanda <i class="fa-solid fa-arrow-right go-to-version"></i></li>
</ul>
</li>
<li data-continent="oceania">
<div class="header">Oceanía <i class="fa-solid fa-search-plus map-zoom"></i></div>
<ul class="countries">
<li data-country-id="au" data-version="au"><img alt="Australia" class="nflag" src="/imgs/countries2/AU.png"/> Australia <i class="fa-solid fa-arrow-right go-to-version"></i></li>
</ul>
</li>
</ul>
<ul class="continents">
<li data-continent="america-south">
<div class="header">América del sur <i class="fa-solid fa-search-plus map-zoom"></i> </div>
<ul class="countries">
<li data-country-id="ar" data-version="ar"><img alt="Argentina" class="nflag" src="/imgs/countries2/AR.png"/> Argentina <i class="fa-solid fa-arrow-right go-to-version"></i></li>
<li data-country-id="cl" data-version="cl"><img alt="Chile" class="nflag" src="/imgs/countries2/CL.png"/> Chile <i class="fa-solid fa-arrow-right go-to-version"></i></li>
<li data-country-id="co" data-version="co"><img alt="Colombia" class="nflag" src="/imgs/countries2/CO.png"/> Colombia <i class="fa-solid fa-arrow-right go-to-version"></i></li>
<li data-country-id="uy" data-version="uy"><img alt="Uruguay" class="nflag" src="/imgs/countries2/UY.png"/> Uruguay <i class="fa-solid fa-arrow-right go-to-version"></i></li>
<li data-country-id="py" data-version="py"><img alt="Paraguay" class="nflag" src="/imgs/countries2/PY.png"/> Paraguay <i class="fa-solid fa-arrow-right go-to-version"></i></li>
<li data-country-id="pe" data-version="pe"><img alt="Perú" class="nflag" src="/imgs/countries2/PE.png"/> Perú <i class="fa-solid fa-arrow-right go-to-version"></i></li>
<li data-country-id="ec" data-version="ec"><img alt="Ecuador" class="nflag" src="/imgs/countries2/EC.png"/> Ecuador <i class="fa-solid fa-arrow-right go-to-version"></i></li>
<li data-country-id="ve" data-version="ve"><img alt="Venezuela" class="nflag" src="/imgs/countries2/VE.png"/> Venezuela <i class="fa-solid fa-arrow-right go-to-version"></i></li>
<li data-country-id="cr" data-version="cr"><img alt="Costa Rica" class="nflag" src="/imgs/countries2/CR.png"/> Costa Rica <i class="fa-solid fa-arrow-right go-to-version"></i></li>

Ahora que hemos repasado lo básico de HTML, podemos empezar a extraer datos de `soup`. Basta con escribir un nombre de etiqueta después de `soup` y un punto (como `soup.title`) y observar cómo se desarrolla la magia:

In [65]:
soup.title

In [66]:
soup.h1

In [67]:
soup.h1.get_text()

'Top FilmAffinity'

¿Qué sucede si solo necesitas el atributo de un elemento?

In [68]:
soup.a

<a href="https://www.filmaffinity.com/es/main.html">
<img alt="logo" src="/images/logo4.png"/>
<div class="logo-siteloc">España</div>
</a>

In [69]:
soup.a['href']

'https://www.filmaffinity.com/es/main.html'

In [70]:
print("Sin utilizar método .find():")
print(soup.a)
print("")
print("Utilizando método .find():")
print(soup.find("a"))

Sin utilizar método .find():
<a href="https://www.filmaffinity.com/es/main.html">
<img alt="logo" src="/images/logo4.png"/>
<div class="logo-siteloc">España</div>
</a>

Utilizando método .find():
<a href="https://www.filmaffinity.com/es/main.html">
<img alt="logo" src="/images/logo4.png"/>
<div class="logo-siteloc">España</div>
</a>

In [71]:
soup.find("a").find('img')['src']

'/images/logo4.png'

In [72]:
soup.find_all('a')

[<a href="https://www.filmaffinity.com/es/main.html">
 <img alt="logo" src="/images/logo4.png"/>
 <div class="logo-siteloc">España</div>
 </a>,
 <a href="https://www.filmaffinity.com/es/advsearch.php">Búsqueda avanzada <i class="fa-solid fa-angle-double-right"></i></a>,
 <a class="sign-in" href="https://www.filmaffinity.com/es/login.php"><strong>Iniciar sesión</strong></a>,
 <a class="register" href="https://www.filmaffinity.com/es/register.php">Registrarse</a>,
 <a href="https://www.filmaffinity.com/es/topgen.php">Top FA</a>,
 <a href="https://www.filmaffinity.com/es/rankings.php">Rankings FA</a>,
 <a href="https://www.filmaffinity.com/es/calendar-tv.php">Calendario Series</a>,
 <a href="https://www.filmaffinity.com/es/category.php?id=TRAILERS">Tráilers</a>,
 <a href="https://www.filmaffinity.com/es/category.php?id=latest_reviews">Críticas</a>,
 <a href="https://www.filmaffinity.com/es/best_2025.php">2025</a>,
 <a href="https://www.filmaffinity.com/es/category.php?id=2026films">2026</a>,
 <a href="https://www.filmaffinity.com/es/all_awards.php">Premios</a>,
 <a href="https://www.filmaffinity.com/es/cinema-guide.php">Guía FilmAffinity <span class="tooltip-new">New</span></a>,
 <a href="https://twitter.com/Filmaffinity" rel="noopener noreferrer" target="_blank" title="Sigue a FA en Twitter (75.000 followers)"><i class="fa-brands fa-x-twitter"></i></a>,
 <a href="https://www.instagram.com/filmaffinity/" rel="noopener noreferrer" target="_blank" title="Sigue a FA en Instagram (155.000 followers)"><i class="fa-brands fa-instagram"></i></a>,
 <a class="more-info" href="https://www.filmaffinity.com/es/fa-international.php"><i class="fa-solid fa-info-circle"></i> Más información</a>,
 <a href="#header-top" title="Ir arriba">
 <img alt="arrow" src="https://www.filmaffinity.com/images/arrow-up2.png"/>
 </a>,
 <a class="rate-tours" href="https://www.filmaffinity.com/es/tours.php">Votar los tours</a>,
 <a class="sign-in" href="https://www.filmaffinity.com/es/login.php">Iniciar sesión</a>,
 <a href="https://www.filmaffinity.com/es/register.php">Registrarse</a>,
 <a href="https://www.filmaffinity.com/es/cat_new_th_es.html">Películas en cartelera</a>,
 <a href="https://www.filmaffinity.com/es/cityTheaters.php">Cines España</a>,
 <a href="https://www.filmaffinity.com/es/rdcat.php?id=upc_th_es">Próximos estrenos</a>,
 <a href="https://www.filmaffinity.com/es/cat_new_sa_es.html">Estrenos Blu-ray venta</a>,
 <a href="https://www.filmaffinity.com/es/rdcat.php?id=upc_sa_es">Próximos Blu-ray venta</a>,
 <a href="https://www.filmaffinity.com/es/cat_new_re_es.html">Ya para alquilar</a>,
 <a href="https://www.filmaffinity.com/es/rdcat.php?id=upc_re_es">Próximamente alquiler</a>,
 <a href="https://www.filmaffinity.com/es/cat_new_netflix.html">Netflix</a>,
 <a href="https://www.filmaffinity.com/es/rdcat.php?id=upc_netflix">Netflix (próx)</a>,
 <a href="https://www.filmaffinity.com/es/cat_new_amazon_es.html">Amazon Prime</a>,
 <a href="https://www.filmaffinity.com/es/cat_new_movistar_f.html">Movistar Plus+ </a>,
 <a href="https://www.filmaffinity.com/es/cat_upc_movistar_f.html">Movistar Plus+ (próx)</a>,
 <a href="https://www.filmaffinity.com/es/cat_new_hbo_es.html">HBO Max</a>,
 <a href="https://www.filmaffinity.com/es/cat_disneyplus.html">Disney+</a>,
 <a href="https://www.filmaffinity.com/es/cat_new_filmin.html">Filmin</a>,
 <a href="https://www.filmaffinity.com/es/cat_apple_tv_plus.html">Apple TV+</a>,
 <a href="https://www.filmaffinity.com/es/cat_skyshowtime.html">SkyShowtime</a>,
 <a href="https://www.filmaffinity.com/es/cat_new_th_us.html">Estrenos USA</a>,
 <a href="https://www.filmaffinity.com/es/cat_new_th_uk.html">Estrenos Reino Unido</a>,
 <a href="https://www.filmaffinity.com/es/cat_new_th_fr.html">Estrenos Francia</a>,
 <a class="Rankings" href="https://www.filmaffinity.com/es/rankings.php">Todos los rankings</a>,
 <a href="https://www.filmaffinity.com/es/ranking.php?rn=ranking_fa_movies">El Top 1000 de FA</a>,
 <a href="https://www.filmaffinity.com/es/boxoffice.php">Taquilla</a>,
 <a href="https://www.filmaffinity.com/es/trailers.php">Trailers</a>,
 <a href="https://www.filmaffinity.com/es/latestevideos.php">Últimos tráilers</a>,
 <a href="https://www.filmaffinity.com/es/latestreviews.php">Últimas críticas users</a>,
 <a href="https://www.filmaffinity.com/es/category.php?id=latest_reviews">Qué dice la crítica</a>,
 <a href="https://www.filmaffinity.com/es/topics.php">Películas por temas</a>,
 <a href="https://www.filmaffinity.com/es/movie-groups-all.php">Sagas &amp; Franquicias</a>,
 <a href="https://www.filmaffinity.com/es/cinema-guide.php">Guía FilmAffinity <span class="tooltip-new ms-1 p-1 text-white">New</span></a>,
 <a href="https://www.filmaffinity.com/es/cat_current_tv.html">Series de actualidad</a>,
 <a href="https://www.filmaffinity.com/es/topgen.php?genres=-DO&amp;chv=1&amp;orderby=avg&amp;movietype=serie%7Conly-serie&amp;country=&amp;fromyear=1874&amp;toyear=2021&amp;ratingcount=3&amp;runtimemin=0&amp;runtimemax=4">Top series</a>,
 <a href="https://www.filmaffinity.com/es/tour.php?idtour=26">Vota Series de TV</a>,
 <a href="https://www.filmaffinity.com/es/topgen.php">Top Filmaffinity</a>,
 <a href="https://www.filmaffinity.com/es/best_tops.php">Lo mejor del TOP</a>,
 <a href="https://www.filmaffinity.com/es/topcat_new_th_es.html">Top Estrenos</a>,
 <a href="https://www.filmaffinity.com/es/topcat_new_sa_es.html">Top Estrenos Blu-ray</a>,
 <a href="https://www.filmaffinity.com/es/listsrank.php">Ranking de listas</a>,
 <a href="https://www.filmaffinity.com/es/all_awards.php">Premios y Festivales</a>,
 <a href="https://www.filmaffinity.com/es/oscar_data.php">Todos los Oscar</a>,
 <a href="https://www.filmaffinity.com/es/best_2025.php">Resumen 2025</a>,
 <a href="https://www.filmaffinity.com/es/site-guide.php">Acerca de FA</a>,
 <a href="https://www.filmaffinity.com/es/contact_us.php">Contacto</a>,
 <a class="btn" data-bs-toggle="popover" data-bs-trigger="focus" id="main-top-share-button" role="button" tabindex="0" title="compartir">
 <i class="fa-solid fa-share-alt"></i>
 </a>,
 <a class="page-link list-view active" data-key-option="list" href="https://www.filmaffinity.com/es//es/topgen.php?orderby=raa&amp;chv=list" title="vista en formato listado"><i class="fa-light fa-table-list"></i></a>,
 <a class="page-link poster-view" data-key-option="grid" href="https://www.filmaffinity.com/es//es/topgen.php?orderby=raa&amp;chv=grid" title="vista en formato pósters"><i class="fa-light fa-table-cells-large"></i></a>,
 <a class="list-group-item py-3 menu-action play-trailer">
 <i class="fa-brands fa-youtube"></i> Play trailer                        </a>,
 <a class="list-group-item py-3 menu-action share-movie">
 <i class="fa-solid fa-share"></i> Share movie card                        </a>,
 <a class="list-group-item py-3 menu-action share-rating" href="https://www.filmaffinity.com/es/user/rating/{user-id}/{movie-id}.html">
 <i class="fa-solid fa-share"></i> Share user rating                        </a>,
 <a href="https://www.filmaffinity.com/es/film809297.html"><div class="mc-poster" style="aspect-ratio: 0.666"><img alt="El padrino " class="lazyload" data-sizes="auto" data-srcset="https://pics.filmaffinity.com/the_godfather-488102675-msmall.jpg 150w, https://pics.filmaffinity.com/the_godfather-488102675-mmed.jpg 300w, https://pics.filmaffinity.com/the_godfather-488102675-large.jpg 400w" src="/images/empty.gif"/></div></a>,
 <a class="d-none d-md-inline-block" href="https://www.filmaffinity.com/es/film809297.html">El padrino</a>,
 <a class="d-md-none stretched-link" href="https://www.filmaffinity.com/es/film809297.html">El padrino</a>,
 <a href="https://www.filmaffinity.com/es/name.php?name-id=845159519" title="Francis Ford Coppola">Francis Ford Coppola</a>,
 <a href="https://www.filmaffinity.com/es/name.php?name-id=847880194" title="Marlon Brando">Marlon Brando</a>,
 <a href="https://www.filmaffinity.com/es/name.php?name-id=951364861" title="Al Pacino">Al Pacino</a>,
 <a href="https://www.filmaffinity.com/es/name.php?name-id=528190012" title="James Caan">James Caan</a>,
 <a class="btn btn-sm btn-outline-secondary py-0 addl" href="https://www.filmaffinity.com/es/edtmovielists.php?movie_id=" title="Añadir a listas"><i class="fa-solid fa-list"></i></a>,
 <a href="https://www.filmaffinity.com/es/film107937.html"><div class="mc-poster" style="aspect-ratio: 0.667"><img alt="Planeta Tierra II (Miniserie de TV)" class="lazyload" data-sizes="auto" data-srcset="https://pics.filmaffinity.com/planet_earth_ii-875634466-msmall.jpg 150w, https://pics.filmaffinity.com/planet_earth_ii-875634466-mmed.jpg 300w, https://pics.filmaffinity.com/planet_earth_ii-875634466-large.jpg 400w" src="/images/empty.gif"/></div></a>,
 <a class="d-none d-md-inline-block" href="https://www.filmaffinity.com/es/film107937.html">Planeta Tierra II</a>,
 <a class="d-md-none stretched-link" href="https://www.filmaffinity.com/es/film107937.html">Planeta Tierra II</a>,
 <a href="https://www.filmaffinity.com/es/name.php?name-id=476508502" title="Elizabeth White">Elizabeth White</a>,
 <a href="https://www.filmaffinity.com/es/name.php?name-id=909122069" title="Justin Anderson">Justin Anderson</a>,
 <a href="https://www.filmaffinity.com/es/name.php?name-id=716377747" title="Ed Charles">Ed Charles</a>,
 <a href="https://www.filmaffinity.com/es/name.php?name-id=390763760" title="David Attenborough">David Attenborough</a>,
 <a class="btn btn-sm btn-outline-secondary py-0 addl" href="https://www.filmaffinity.com/es/edtmovielists.php?movie_id=" title="Añadir a listas"><i class="fa-solid fa-list"></i></a>,
 <a href="https://www.filmaffinity.com/es/film730528.html"><div class="mc-poster" style="aspect-ratio: 0.658"><img alt="El padrino. Parte II " class="lazyload" data-sizes="auto" data-srcset="https://pics.filmaffinity.com/the_godfather_part_ii-617901053-msmall.jpg 150w, https://pics.filmaffinity.com/the_godfather_part_ii-617901053-mmed.jpg 300w, https://pics.filmaffinity.com/the_godfather_part_ii-617901053-large.jpg 400w" src="/images/empty.gif"/></div></a>,
 <a class="d-none d-md-inline-block" href="https://www.filmaffinity.com/es/film730528.html">El padrino. Parte II</a>,
 <a class="d-md-none stretched-link" href="https://www.filmaffinity.com/es/film730528.html">El padrino. Parte II</a>,
 <a href="https://www.filmaffinity.com/es/name.php?name-id=845159519" title="Francis Ford Coppola">Francis Ford Coppola</a>,
 <a href="https://www.filmaffinity.com/es/name.php?name-id=951364861" title="Al Pacino">Al Pacino</a>,
 <a href="https://www.filmaffinity.com/es/name.php?name-id=627577077" title="Robert De Niro">Robert De Niro</a>,
 <a href="https://www.filmaffinity.com/es/name.php?name-id=568095076" title="Diane Keaton">Diane Keaton</a>,
 <a class="btn btn-sm btn-outline-secondary py-0 addl" href="https://www.filmaffinity.com/es/edtmovielists.php?movie_id=" title="Añadir a listas"><i class="fa-solid fa-list"></i></a>,
 <a href="https://www.filmaffinity.com/es/film399474.html"><div class="mc-poster" style="aspect-ratio: 0.662"><img alt="The Wire (Bajo escucha) (Serie de TV)" class="lazyload" data-sizes="auto" data-srcset="https://pics.filmaffinity.com/the_wire-680717276-msmall.jpg 150w, https://pics.filmaffinity.com/the_wire-680717276-mmed.jpg 300w, https://pics.filmaffinity.com/the_wire-680717276-large.jpg 400w" src="/images/empty.gif"/></div></a>,
 <a class="d-none d-md-inline-block" href="https://www.filmaffinity.com/es/film399474.html">The Wire (Bajo escucha)</a>,
 <a class="d-md-none stretched-link" href="https://www.filmaffinity.com/es/film399474.html">The Wire (Bajo escucha)</a>,
 <a href="https://www.filmaffinity.com/es/name.php?name-id=237180108" title="David Simon">David Simon</a>,
 <a href="https://www.filmaffinity.com/es/name.php?name-id=791341213" title="Joe Chappelle">Joe Chappelle</a>,
 <a href="https://www.filmaffinity.com/es/name.php?name-id=957834405" title="Dominic West">Dominic West</a>,
 <a href="https://www.filmaffinity.com/es/name.php?name-id=851376245" title="Lance Reddick">Lance Reddick</a>,
 <a href="https://www.filmaffinity.com/es/name.php?name-id=498301404" title="Sonja Sohn">Sonja Sohn</a>,
 <a class="btn btn-sm btn-outline-secondary py-0 addl" href="https://www.filmaffinity.com/es/edtmovielists.php?movie_id=" title="Añadir a listas"><i class="fa-solid fa-list"></i></a>,
 <a href="https://www.filmaffinity.com/es/film489970.html"><div class="mc-poster" style="aspect-ratio: 0.68"><img alt="Breaking Bad (Serie de TV)" class="lazyload" data-sizes="auto" data-srcset="https://pics.filmaffinity.com/breaking_bad-504442815-msmall.jpg 150w, https://pics.filmaffinity.com/breaking_bad-504442815-mmed.jpg 300w, https://pics.filmaffinity.com/breaking_bad-504442815-large.jpg 400w" src="/images/empty.gif"/></div></a>,
 <a class="d-none d-md-inline-block" href="https://www.filmaffinity.com/es/film489970.html">Breaking Bad</a>,
 <a class="d-md-none stretched-link" href="https://www.filmaffinity.com/es/film489970.html">Breaking Bad</a>,
 <a href="https://www.filmaffinity.com/es/name.php?name-id=459610705" title="Vince Gilligan">Vince Gilligan</a>,
 <a href="https://www.filmaffinity.com/es/name.php?name-id=848463658" title="Michelle MacLaren">Michelle MacLaren</a>,
 <a href="https://www.filmaffinity.com/es/name.php?name-id=255063027" title="Bryan Cranston">Bryan Cranston</a>,
 <a href="https://www.filmaffinity.com/es/name.php?name-id=341369862" title="Aaron Paul">Aaron Paul</a>,
 <a href="https://www.filmaffinity.com/es/name.php?name-id=313717763" title="Anna Gunn">Anna Gunn</a>,
 <a class="btn btn-sm btn-outline-secondary py-0 addl" href="https://www.filmaffinity.com/es/edtmovielists.php?movie_id=" title="Añadir a listas"><i class="fa-solid fa-list"></i></a>,
 <a href="https://www.filmaffinity.com/es/film601451.html"><div class="mc-poster" style="aspect-ratio: 0.711"><img alt="Cosmos (Serie de TV)" class="lazyload" data-sizes="auto" data-srcset="https://pics.filmaffinity.com/cosmos-224838468-msmall.jpg 150w, https://pics.filmaffinity.com/cosmos-224838468-mmed.jpg 300w, https://pics.filmaffinity.com/cosmos-224838468-large.jpg 400w" src="/images/empty.gif"/></div></a>,
 <a class="d-none d-md-inline-block" href="https://www.filmaffinity.com/es/film601451.html">Cosmos</a>,
 <a class="d-md-none stretched-link" href="https://www.filmaffinity.com/es/film601451.html">Cosmos</a>,
 <a href="https://www.filmaffinity.com/es/name.php?name-id=970498708" title="Carl Sagan">Carl Sagan</a>,
 <a href="https://www.filmaffinity.com/es/name.php?name-id=692371906" title="David F. Oyster">David F. Oyster</a>,
 <a href="https://www.filmaffinity.com/es/name.php?name-id=771217020" title="Adrian Malone">Adrian Malone</a>,
 <a href="https://www.filmaffinity.com/es/name.php?name-id=970498708" title="Carl Sagan">Carl Sagan</a>,
 <a class="btn btn-sm btn-outline-secondary py-0 addl" href="https://www.filmaffinity.com/es/edtmovielists.php?movie_id=" title="Añadir a listas"><i class="fa-solid fa-list"></i></a>,
 <a href="https://www.filmaffinity.com/es/film518489.html"><div class="mc-poster" style="aspect-ratio: 0.727"><img alt="Planeta azul II (Miniserie de TV)" class="lazyload" data-sizes="auto" data-srcset="https://pics.filmaffinity.com/blue_planet_ii-415010287-msmall.jpg 150w, https://pics.filmaffinity.com/blue_planet_ii-415010287-mmed.jpg 300w, https://pics.filmaffinity.com/blue_planet_ii-415010287-large.jpg 400w" src="/images/empty.gif"/></div></a>,
 <a class="d-none d-md-inline-block" href="https://www.filmaffinity.com/es/film518489.html">Planeta azul II</a>,
 <a class="d-md-none stretched-link" href="https://www.filmaffinity.com/es/film518489.html">Planeta azul II</a>,
 <a href="https://www.filmaffinity.com/es/name.php?name-id=390763760" title="David Attenborough">David Attenborough</a>,
 <a href="https://www.filmaffinity.com/es/name.php?name-id=390763760" title="David Attenborough">David Attenborough</a>,
 <a class="btn btn-sm btn-outline-secondary py-0 addl" href="https://www.filmaffinity.com/es/edtmovielists.php?movie_id=" title="Añadir a listas"><i class="fa-solid fa-list"></i></a>,
 <a href="https://www.filmaffinity.com/es/film695552.html"><div class="mc-poster" style="aspect-ratio: 0.669"><img alt="Doce hombres sin piedad " class="lazyload" data-sizes="auto" data-srcset="https://pics.filmaffinity.com/12_angry_men-122099105-msmall.jpg 150w, https://pics.filmaffinity.com/12_angry_men-122099105-mmed.jpg 300w, https://pics.filmaffinity.com/12_angry_men-122099105-large.jpg 400w" src="/images/empty.gif"/></div></a>,
 <a class="d-none d-md-inline-block" href="https://www.filmaffinity.com/es/film695552.html">Doce hombres sin piedad</a>,
 <a class="d-md-none stretched-link" href="https://www.filmaffinity.com/es/film695552.html">Doce hombres sin piedad</a>,
 <a href="https://www.filmaffinity.com/es/name.php?name-id=435435282" title="Sidney Lumet">Sidney Lumet</a>,
 <a href="https://www.filmaffinity.com/es/name.php?name-id=467312909" title="Henry Fonda">Henry Fonda</a>,
 <a href="https://www.filmaffinity.com/es/name.php?name-id=684564393" title="Lee J. Cobb">Lee J. Cobb</a>,
 <a href="https://www.filmaffinity.com/es/name.php?name-id=324872468" title="Jack Warden">Jack Warden</a>,
 <a class="btn btn-sm btn-outline-secondary py-0 addl" href="https://www.filmaffinity.com/es/edtmovielists.php?movie_id=" title="Añadir a listas"><i class="fa-solid fa-list"></i></a>,
 <a href="https://www.filmaffinity.com/es/film661074.html"><div class="mc-poster" style="aspect-ratio: 0.675"><img alt="Cosmos: A Space-Time Odyssey (Serie de TV)" class="lazyload" data-sizes="auto" data-srcset="https://pics.filmaffinity.com/cosmos_a_space_time_odyssey-358329014-msmall.jpg 150w, https://pics.filmaffinity.com/cosmos_a_space_time_odyssey-358329014-mmed.jpg 300w, https://pics.filmaffinity.com/cosmos_a_space_time_odyssey-358329014-large.jpg 400w" src="/images/empty.gif"/></div></a>,
 <a class="d-none d-md-inline-block" href="https://www.filmaffinity.com/es/film661074.html">Cosmos: A Space-Time Odyssey</a>,
 <a class="d-md-none stretched-link" href="https://www.filmaffinity.com/es/film661074.html">Cosmos: A Space-Time Odyssey</a>,
 <a href="https://www.filmaffinity.com/es/name.php?name-id=208744758" title="Ann Druyan">Ann Druyan</a>,
 <a href="https://www.filmaffinity.com/es/name.php?name-id=522491990" title="Steven Soter">Steven Soter</a>,
 <a href="https://www.filmaffinity.com/es/name.php?name-id=332669308" title="Neil deGrasse Tyson">Neil deGrasse Tyson</a>,
 <a href="https://www.filmaffinity.com/es/name.php?name-id=257254204" title="Seth MacFarlane">Seth MacFarlane</a>,
 <a class="btn btn-sm btn-outline-secondary py-0 addl" href="https://www.filmaffinity.com/es/edtmovielists.php?movie_id=" title="Añadir a listas"><i class="fa-solid fa-list"></i></a>,
 <a href="https://www.filmaffinity.com/es/film656153.html"><div class="mc-poster" style="aspect-ratio: 0.676"><img alt="La lista de Schindler " class="lazyload" data-sizes="auto" data-srcset="https://pics.filmaffinity.com/schindler_s_list-473662617-msmall.jpg 150w, https://pics.filmaffinity.com/schindler_s_list-473662617-mmed.jpg 300w, https://pics.filmaffinity.com/schindler_s_list-473662617-large.jpg 400w" src="/images/empty.gif"/></div></a>,
 <a class="d-none d-md-inline-block" href="https://www.filmaffinity.com/es/film656153.html">La lista de Schindler</a>,
 <a class="d-md-none stretched-link" href="https://www.filmaffinity.com/es/film656153.html">La lista de Schindler</a>,
 <a href="https://www.filmaffinity.com/es/name.php?name-id=452047124" title="Steven Spielberg">Steven Spielberg</a>,
 <a href="https://www.filmaffinity.com/es/name.php?name-id=250177862" title="Liam Neeson">Liam Neeson</a>,
 <a href="https://www.filmaffinity.com/es/name.php?name-id=868507788" title="Ben Kingsley">Ben Kingsley</a>,
 <a href="https://www.filmaffinity.com/es/name.php?name-id=157702971" title="Ralph Fiennes">Ralph Fiennes</a>,

In [73]:
all_a = soup.find_all('a')
for a in all_a[:5]:
    print(a)

<a href="https://www.filmaffinity.com/es/main.html">
<img alt="logo" src="/images/logo4.png"/>
<div class="logo-siteloc">España</div>
</a>
<a href="https://www.filmaffinity.com/es/advsearch.php">Búsqueda avanzada <i class="fa-solid fa-angle-double-right"></i></a>
<a class="sign-in" href="https://www.filmaffinity.com/es/login.php"><strong>Iniciar sesión</strong></a>
<a class="register" href="https://www.filmaffinity.com/es/register.php">Registrarse</a>
<a href="https://www.filmaffinity.com/es/topgen.php">Top FA</a>

In [74]:
all_a = soup.find_all('a')
for a in all_a[:5]:
    print(a.get_text()) # Si no tiene texto, esto peta, tener cuidado.

España

Búsqueda avanzada
Iniciar sesión
Registrarse
Top FA

In [75]:
all_a = soup.find_all('a')
for a in all_a[:5]:
    print(a['href'])

https://www.filmaffinity.com/es/main.html
https://www.filmaffinity.com/es/advsearch.php
https://www.filmaffinity.com/es/login.php
https://www.filmaffinity.com/es/register.php
https://www.filmaffinity.com/es/topgen.php

In [76]:
all_a = soup.find_all('a')[4:13]
coleccion = dict()
for a in all_a:
    coleccion[a.get_text()] = a['href']
    print(a.get_text())
    print(a['href'])

print(coleccion)
df = pd.DataFrame.from_dict(coleccion, orient="index", columns=["Link"])

Top FA
https://www.filmaffinity.com/es/topgen.php
Rankings FA
https://www.filmaffinity.com/es/rankings.php
Calendario Series
https://www.filmaffinity.com/es/calendar-tv.php
Tráilers
https://www.filmaffinity.com/es/category.php?id=TRAILERS
Críticas
https://www.filmaffinity.com/es/category.php?id=latest_reviews
2025
https://www.filmaffinity.com/es/best_2025.php
2026
https://www.filmaffinity.com/es/category.php?id=2026films
Premios
https://www.filmaffinity.com/es/all_awards.php
Guía FilmAffinity New
https://www.filmaffinity.com/es/cinema-guide.php
{'Top FA': 'https://www.filmaffinity.com/es/topgen.php', 'Rankings FA': 'https://www.filmaffinity.com/es/rankings.php', 'Calendario Series': 'https://www.filmaffinity.com/es/calendar-tv.php', 'Tráilers': 'https://www.filmaffinity.com/es/category.php?id=TRAILERS', 'Críticas': 'https://www.filmaffinity.com/es/category.php?id=latest_reviews', '2025': 'https://www.filmaffinity.com/es/best_2025.php', '2026': 'https://www.filmaffinity.com/es/category.php?id=2026films', 'Premios': 'https://www.filmaffinity.com/es/all_awards.php', 'Guía FilmAffinity New': 'https://www.filmaffinity.com/es/cinema-guide.php'}

In [77]:
df

                                                                                 Link
Top FA                                     https://www.filmaffinity.com/es/topgen.php
Rankings FA                              https://www.filmaffinity.com/es/rankings.php
Calendario Series                     https://www.filmaffinity.com/es/calendar-tv.php
Tráilers                     https://www.filmaffinity.com/es/category.php?id=TRAILERS
Críticas               https://www.filmaffinity.com/es/category.php?id=latest_reviews
2025                                    https://www.filmaffinity.com/es/best_2025.php
2026                        https://www.filmaffinity.com/es/category.php?id=2026films
Premios                                https://www.filmaffinity.com/es/all_awards.php
Guía FilmAffinity New                https://www.filmaffinity.com/es/cinema-guide.php

<table align="left">
 <tr><td width="80"><img src="./img/ejercicio.png" style="width:auto;height:auto"></td>
     <td style="text-align:left">
         <h3>Obtener textos menú cabecera</h3>
Textos del menú de la cabecera (Top FA, Rankings FA, Calendario Series, Tráilers, Críticas, ...)
      
<ol>
    <li>Obtén los textos con find_all y un bucle</li>
    <li>Obtén los links con find_all y un bucle</li>
    <li>Almacena la información en un dataframe</li>
</ol>
         
 </td></tr>
</table>

In [78]:
for x in soup.find_all("a")[4:13]:
    print(x.get_text())
    print(x['href'])

Top FA
https://www.filmaffinity.com/es/topgen.php
Rankings FA
https://www.filmaffinity.com/es/rankings.php
Calendario Series
https://www.filmaffinity.com/es/calendar-tv.php
Tráilers
https://www.filmaffinity.com/es/category.php?id=TRAILERS
Críticas
https://www.filmaffinity.com/es/category.php?id=latest_reviews
2025
https://www.filmaffinity.com/es/best_2025.php
2026
https://www.filmaffinity.com/es/category.php?id=2026films
Premios
https://www.filmaffinity.com/es/all_awards.php
Guía FilmAffinity New
https://www.filmaffinity.com/es/cinema-guide.php

In [79]:
dict_enlaces = {"Titulo": [],
                "Enlace": []}

for x in soup.find_all("a")[4:13]:
    print(x.get_text())
    dict_enlaces['Titulo'].append(x.get_text())
    # print(x['href'])
    dict_enlaces['Enlace'].append(x['href'])

df_titulos = pd.DataFrame(dict_enlaces)
df_titulos.to_csv("data/titulos.csv")
df_titulos

Top FA
Rankings FA
Calendario Series
Tráilers
Críticas
2025
2026
Premios
Guía FilmAffinity New

OSError: Cannot save file into a non-existent directory: 'data'

In [ ]:
for x in soup.find("ul", id="awardsmenu").find_all('a'):
    print(x.get_text())
    print(x['href'])

Top FA
https://www.filmaffinity.com/es/topgen.php
Rankings FA
https://www.filmaffinity.com/es/rankings.php
Calendario Series
https://www.filmaffinity.com/es/calendar-tv.php
Tráilers
https://www.filmaffinity.com/es/category.php?id=TRAILERS
Críticas
https://www.filmaffinity.com/es/category.php?id=latest_reviews
2025
https://www.filmaffinity.com/es/best_2025.php
2026
https://www.filmaffinity.com/es/category.php?id=2026films
Premios
https://www.filmaffinity.com/es/all_awards.php
Guía FilmAffinity New
https://www.filmaffinity.com/es/cinema-guide.php

In [ ]:
dict_enlaces = {"Titulo": [x.get_text() for x in soup.find("ul", id="awardsmenu").find_all('a')],
                "Enlace": [x['href'] for x in soup.find("ul", id="awardsmenu").find_all('a')]}

df_titulos = pd.DataFrame(dict_enlaces)
df_titulos.to_csv("data/titulos.csv")
df_titulos

,Titulo,Enlace
0,Top FA,https://www.filmaffinity.com/es/topgen.php
1,Rankings FA,https://www.filmaffinity.com/es/rankings.php
2,Calendario Series,https://www.filmaffinity.com/es/calendar-tv.php
3,Tráilers,https://www.filmaffinity.com/es/category.php?id=TRAILERS
4,Críticas,https://www.filmaffinity.com/es/category.php?id=latest_reviews
5,2025,https://www.filmaffinity.com/es/best_2025.php
6,2026,https://www.filmaffinity.com/es/category.php?id=2026films
7,Premios,https://www.filmaffinity.com/es/all_awards.php
8,Guía FilmAffinity New,https://www.filmaffinity.com/es/cinema-guide.php

<table align="left">
 <tr><td width="80"><img src="./img/ejercicio.png" style="width:auto;height:auto"></td>
     <td style="text-align:left">
         <h3>Obtener películas y nota</h3>
      
<ol>
    <li>Obtén los títulos de las top 10 películas</li>
    <li>Obtén el rating de las top 10 películas</li>
    <li>Almacena la información en un dataframe</li>
</ol>
         
 </td></tr>
</table>

In [ ]:
for x in soup.find_all("div", class_="mc-title")[:10]:
    print(x.find('a').get_text())

El padrino
Planeta Tierra II
El padrino. Parte II
The Wire (Bajo escucha)
Breaking Bad
Cosmos
Planeta azul II
Doce hombres sin piedad
Cosmos: A Space-Time Odyssey
La lista de Schindler

In [ ]:
for x in soup.find_all("div", class_='avg'):
    print(x.get_text())

9,0
9,0
9,0
8,9
8,9
8,9
8,9
8,9
8,9
8,8
8,8
8,8
8,8
8,8
8,8
8,8
8,8
8,8
8,7
8,7
8,7
8,7
8,7
8,7
8,6
8,6
8,6
8,6
8,6
8,6
8,6
8,6
8,6
8,6
8,6
8,6
8,6
8,6
8,6
8,6
8,6
8,6
8,6
8,6
8,6
8,6
8,6
8,6
8,6
8,6
8,6
8,6
8,6
8,6
8,5
8,5
8,5
8,5
8,5
8,5
8,5
8,5
8,5
8,5
8,5
8,5
8,5
8,5
8,5
8,5
8,5
8,5
8,5
8,5
8,5
8,5
8,5
8,5
8,5
8,5
8,5
8,5
8,5
8,5
8,5
8,5
8,5
8,5
8,5
8,5

In [83]:
top10 = {"Titulo": [x.find('a').get_text() for x in soup.find_all("div", class_="mc-title")[:10]],
         "Rating": [float(x.get_text().replace(",",'.')) for x in soup.find_all("div", class_='avg')[:10]]}
df10 = pd.DataFrame(top10, index=range(1,11))
df10.to_csv("data/top10.csv")
df10

                          Titulo  Rating
1                     El padrino     9.0
2              Planeta Tierra II     9.0
3           El padrino. Parte II     9.0
4        The Wire (Bajo escucha)     8.9
5                   Breaking Bad     8.9
6                         Cosmos     8.9
7                Planeta azul II     8.9
8        Doce hombres sin piedad     8.9
9   Cosmos: A Space-Time Odyssey     8.9
10         La lista de Schindler     8.8

In [61]:
top10 = {"Titulo": [],
         "Rating": []}

for x in soup.find_all("div", class_="mc-title")[:10]:
    top10['Titulo'].append(x.find('a').get_text())

for x in soup.find_all("div", class_='avg')[:10]:
    top10['Rating'].append(float(x.get_text().replace(',','.')))

df10 = pd.DataFrame(top10, index=range(1,11))
df10.to_csv("data/top10.csv")
df10

                          Titulo  Rating
1                     El padrino     9.0
2              Planeta Tierra II     9.0
3           El padrino. Parte II     9.0
4        The Wire (Bajo escucha)     8.9
5                   Breaking Bad     8.9
6                         Cosmos     8.9
7                Planeta azul II     8.9
8        Doce hombres sin piedad     8.9
9   Cosmos: A Space-Time Odyssey     8.9
10         La lista de Schindler     8.8

### **Cuidado: emparejar listas por posición**

Las dos soluciones anteriores obtienen los títulos y las notas con **dos `find_all` independientes** y las juntan por posición. Parece que funciona, pero **el resultado es incorrecto**: fíjate en que hay 30 películas y, sin embargo, la celda que imprime todos los `div.avg` muestra 90 notas. FilmAffinity repite cada nota 3 veces en el HTML (versión escritorio, versión móvil y ficha), así que la lista de notas queda `[9.0, 9.0, 9.0, 8.9, 8.9, 8.9, ...]` y a *Planeta Tierra II* le asignamos el 9,0 de *El padrino*. Y lo peor: **no salta ningún error**.

La forma robusta es localizar primero el **contenedor de cada película** (`div.movie-card`) y extraer todos sus campos desde ese mismo nodo. Así título y nota siempre pertenecen a la misma película, y si falta un campo lo dejamos como `None` en lugar de desplazar el resto.

In [84]:
top10 = {"Titulo": [],
         "Rating": []}

for card in soup.find_all("div", class_="movie-card")[:10]:
    titulo = card.find("div", class_="mc-title").find("a").get_text(strip=True)
    nota = card.find("div", class_="avg")

    top10["Titulo"].append(titulo)
    top10["Rating"].append(float(nota.get_text().replace(",", ".")) if nota else None)

df10 = pd.DataFrame(top10, index=range(1, 11))
df10.to_csv("data/top10.csv")
df10

                          Titulo  Rating
1                     El padrino     9.0
2              Planeta Tierra II     8.9
3           El padrino. Parte II     8.9
4        The Wire (Bajo escucha)     8.8
5                   Breaking Bad     8.8
6                         Cosmos     8.8
7                Planeta azul II     8.7
8        Doce hombres sin piedad     8.7
9   Cosmos: A Space-Time Odyssey     8.6
10         La lista de Schindler     8.6