# Ex1 - Filtering and Sorting Data



### Step 1. Import the necessary libraries

In [4]:
import numpy as np
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv).

In [7]:
chipo = pd.read_table("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv",index_col="order_id")

### Step 3. Assign it to a variable called chipo.

In [8]:
chipo

,quantity,item_name,choice_description,item_price
order_id,,,,
1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,Izze,[Clementine],$3.39
1,1,Nantucket Nectar,[Apple],$3.39
1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...
1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [9]:
chipo.shape

(4622, 4)

# Name of the max valued product

In [12]:
chipo.max().item_name

'Veggie Soft Tacos'

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39
1,1,1,Izze,[Clementine],3.39
2,1,1,Nantucket Nectar,[Apple],3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",8.75

3598    Chips and Fresh Tomato Salsa
Name: item_name, dtype: object

                         item_name
3598  Chips and Fresh Tomato Salsa

'Chips and Fresh Tomato Salsa'

### Step 4. How many products cost more than $10.00?

In [77]:

total = len(chipo[((chipo.item_price).str.replace("$","").astype(float) > 10)])
total



# Tiene que haber una mascara, pero no me sale

1130

### Step 5. What is the price of each item? 
###### print a data frame with only two columns item_name and item_price

In [41]:
chipo2 = pd.DataFrame(chipo, columns=["item_name","item_price"])
chipo2

                                      item_name item_price
order_id
1                  Chips and Fresh Tomato Salsa     $2.39
1                                          Izze     $3.39
1                              Nantucket Nectar     $3.39
1         Chips and Tomatillo-Green Chili Salsa     $2.39
2                                  Chicken Bowl    $16.98
...                                         ...        ...
1833                              Steak Burrito    $11.75
1833                              Steak Burrito    $11.75
1834                         Chicken Salad Bowl    $11.25
1834                         Chicken Salad Bowl     $8.75
1834                         Chicken Salad Bowl     $8.75

[4622 rows x 2 columns]

### Step 6. Sort by the name of the item

In [42]:
chipo3 = chipo2.copy()
chipo3.sort_values("item_name")

                  item_name item_price
order_id
1360      6 Pack Soft Drink    $12.98
148       6 Pack Soft Drink     $6.49
749       6 Pack Soft Drink     $6.49
754       6 Pack Soft Drink     $6.49
1076      6 Pack Soft Drink     $6.49
...                     ...        ...
948       Veggie Soft Tacos     $8.75
322       Veggie Soft Tacos     $8.75
1132      Veggie Soft Tacos     $8.49
688       Veggie Soft Tacos    $11.25
567       Veggie Soft Tacos     $8.49

[4622 rows x 2 columns]

### Step 7. What was the quantity of the most expensive item ordered? 2 ways

V1

In [125]:
chipo2 = chipo.copy()
chipo2.item_price = (chipo2.item_price.str.replace("$","").astype("float"))
chipo3 = chipo2.sort_values("item_price", ascending=False)
chipo3.quantity[:1]

order_id
1443    15
Name: quantity, dtype: int64

V2

In [117]:
chipo3.iloc[0].loc[["quantity"]]

quantity    15
Name: 1443, dtype: object

### Step 8. How many times was a Veggie Salad Bowl ordered?

18

### Step 9. How many times did someone order more than one Canned Soda?

20