### Introduction:

The following exercise utilizes data from [UC Irvine Machine Learning Repository](https://archive.ics.uci.edu/ml/datasets/Auto+MPG)

### Step 1. Import the necessary libraries

In [1]:
import numpy as np
import pandas as pd

### Step 2. Import the first dataset [cars1](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars1.csv) and [cars2](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars2.csv).

   ### Step 3. Assign each to a to a variable called cars1 and cars2

In [2]:
cars1 = pd.read_csv("./cars1.csv")
cars2 = pd.read_csv("./cars2.csv")

### Step 4. Oops, it seems our first dataset has some unnamed blank columns, fix cars1

In [3]:
cars1.dropna(axis=1, inplace=True)
cars1

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302,140,3449,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...,...
193,24.0,6,200,81,3012,17.6,76,1,ford maverick
194,22.5,6,232,90,3085,17.6,76,1,amc hornet
195,29.0,4,85,52,2035,22.2,76,1,chevrolet chevette
196,24.5,4,98,60,2164,22.1,76,1,chevrolet woody
197,29.0,4,90,70,1937,14.2,76,2,vw rabbit

### Step 5. What is the number of observations in each dataset?

In [4]:
print(cars1.shape)
print(cars2.shape)

(198, 9)
(200, 9)

### Step 6. Join cars1 and cars2 into a single DataFrame called cars

In [5]:
cars = pd.concat((cars1, cars2))
cars

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302,140,3449,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...,...
195,27.0,4,140,86,2790,15.6,82,1,ford mustang gl
196,44.0,4,97,52,2130,24.6,82,2,vw pickup
197,32.0,4,135,84,2295,11.6,82,1,dodge rampage
198,28.0,4,120,79,2625,18.6,82,1,ford ranger
199,31.0,4,119,82,2720,19.4,82,1,chevy s-10

### Step 7. Oops, there is a column missing, called owners. Create a random number Series from 15,000 to 73,000.

In [11]:
cars["owners"] = np.random.randint(15000,73001,size= cars.shape[0])
cars

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car,owners
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu,21319
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320,21395
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite,70820
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst,66310
4,17.0,8,302,140,3449,10.5,70,1,ford torino,29667
...,...,...,...,...,...,...,...,...,...,...
195,27.0,4,140,86,2790,15.6,82,1,ford mustang gl,61138
196,44.0,4,97,52,2130,24.6,82,2,vw pickup,40634
197,32.0,4,135,84,2295,11.6,82,1,dodge rampage,34985
198,28.0,4,120,79,2625,18.6,82,1,ford ranger,51395
199,31.0,4,119,82,2720,19.4,82,1,chevy s-10,19449

In [12]:
cars.info()

<class 'pandas.DataFrame'>
Index: 398 entries, 0 to 199
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    int64
 3   horsepower    398 non-null    str
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model         398 non-null    int64
 7   origin        398 non-null    int64
 8   car           398 non-null    str
 9   owners        398 non-null    int64
dtypes: float64(2), int64(6), str(2)
memory usage: 34.2 KB

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,owner
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu,NaN,NaN,NaN,NaN,NaN,52424
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320,NaN,NaN,NaN,NaN,NaN,44668
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite,NaN,NaN,NaN,NaN,NaN,35643
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst,NaN,NaN,NaN,NaN,NaN,48149
4,17.0,8,302,140,3449,10.5,70,1,ford torino,NaN,NaN,NaN,NaN,NaN,49329
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,27.0,4,140,86,2790,15.6,82,1,ford mustang gl,NaN,NaN,NaN,NaN,NaN,64171
196,44.0,4,97,52,2130,24.6,82,2,vw pickup,NaN,NaN,NaN,NaN,NaN,24845
197,32.0,4,135,84,2295,11.6,82,1,dodge rampage,NaN,NaN,NaN,NaN,NaN,69233
198,28.0,4,120,79,2625,18.6,82,1,ford ranger,NaN,NaN,NaN,NaN,NaN,35276
199,31.0,4,119,82,2720,19.4,82,1,chevy s-10,NaN,NaN,NaN,NaN,NaN,49921

### Step 8. Add the column owners to cars

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,ownsers,owners
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu,NaN,NaN,NaN,NaN,NaN,53251,27606
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320,NaN,NaN,NaN,NaN,NaN,59422,49090
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite,NaN,NaN,NaN,NaN,NaN,37971,67750
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst,NaN,NaN,NaN,NaN,NaN,26677,51476
4,17.0,8,302,140,3449,10.5,70,1,ford torino,NaN,NaN,NaN,NaN,NaN,36778,23633
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,27.0,4,140,86,2790,15.6,82,1,ford mustang gl,NaN,NaN,NaN,NaN,NaN,60497,63289
196,44.0,4,97,52,2130,24.6,82,2,vw pickup,NaN,NaN,NaN,NaN,NaN,21235,37321
197,32.0,4,135,84,2295,11.6,82,1,dodge rampage,NaN,NaN,NaN,NaN,NaN,17390,51911
198,28.0,4,120,79,2625,18.6,82,1,ford ranger,NaN,NaN,NaN,NaN,NaN,59976,36185
199,31.0,4,119,82,2720,19.4,82,1,chevy s-10,NaN,NaN,NaN,NaN,NaN,28733,71615